// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "mediaplayer1.h"

/////////////////////////////////////////////////////////////////////////////
// CMediaplayer1

IMPLEMENT_DYNCREATE(CMediaplayer1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CMediaplayer1 properties

/////////////////////////////////////////////////////////////////////////////
// CMediaplayer1 operations
